version: '3.0'
services:
  python:
    build:
      context: .
    volumes:
      - './:/lineup'
    ports:
      - '8080:8080'
    links:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      - 'POSTGRES_PASSWORD=lineup'
      - 'POSTGRES_USER=lineup'
      - 'POSTGRES_DB=lineup'
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=lineup@lineup.js.org'
      - 'PGADMIN_DEFAULT_PASSWORD=lineup'
    ports:
      - '8090:80'
