version: '3.0'
services:
  python:
    build:
      context: .
    volumes:
      - './:/lineup'
    ports:
      - '8080:8080'
    links:
      - postgres
  postgres:
    image: postgres:10-alpine
    environment:
      - 'POSTGRES_PASSWORD=lineup'
      - 'POSTGRES_USER=lineup'
      - 'POSTGRES_DB=lineup'
