version: 2
jobs:
  build:
    working_directory: ~/lineup
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: revert package-lock.json
          command: git checkout package-lock.json
      - save_cache:
          key: deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
      - restore_cache:
          key: deps-e-{{ checksum "electron/package.tmpl.json" }}
      - run:
          name: dist
          command: npm run dist
      - save_cache:
          key: deps-e-{{ checksum "electron/package.tmpl.json" }}
          paths:
          - ./electron/node_modules
      - store_artifacts:
          path: dist
      - run: #update build doc and readme
          name: update api
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ "${CIRCLE_BRANCH}" == "develop" ] ; then
                git clone git@github.com:lineupjs/lineupjs.github.io.git
                cd lineupjs.github.io
                appdir=app
                if [ "${CIRCLE_BRANCH}" == "develop" ] ; then
                  appdir=app_develop
                fi
                rm -rf "${appdir}/"
                mv ../build "${appdir}"
                git config user.email "sam@sgratzl.com"
                git config user.name "Samuel Gratzl"
                git add -A
                git commit -m "auto updating ${appdir}" -m "trigger: ${CIRCLE_BUILD_URL}"
                git push origin master
            fi

workflows:
  version: 2
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
